server:
  listen: [ 127.0.0.1@5375 ]
  rundir: .
  udp-workers: 1

database:
  storage: .

log:
  - target: stdout
    any: info

acl:
  - id: localhost
    address: 127.0.0.1
    action: transfer

policy:
  - id: manual
    manual: on

zone:
  - domain: unsigned.test.
    file: /home/pspacek/w/ietf/deleg-wg/testvec/unsigned.test.zone

  - domain: nsec.test.
    file: /home/pspacek/w/ietf/deleg-wg/testvec/nsec.test.zone
    acl: localhost
    dnssec-signing: on
    dnssec-policy: manual
