server:
  listen: [ 127.0.0.1@5375 ]
  rundir: /tmp
  udp-workers: 1

database:
  storage: /tmp

log:
  - target: stdout
    any: info

zone:
  - domain: test.
    file: /home/pspacek/w/ietf/deleg-wg/testvec/zone
