server:
  listen: [ 127.0.0.1@5375 ]
  rundir: .
  udp-workers: 1

database:
  storage: .

log:
  - target: stdout
    any: info

acl:
  - id: localhost
    address: 127.0.0.1
    action: transfer

policy:
  - id: nsec
    reproducible-signing: on
    manual: on

policy:
  - id: nsec3
    manual: on
    reproducible-signing: on
    nsec3: on

policy:
  - id: optout-nsec3
    manual: on
    reproducible-signing: on
    nsec3: on
    nsec3-opt-out: on

template:
  - id: default
    storage: .
    semantic-checks: on
    acl: localhost
    deleg-aware: on
    file: %s.zone
    dnssec-signing: on

zone:
  - domain: unsigned.test.
    file: unsigned.test.zone
    dnssec-signing: off

  - domain: nsec.test.
    dnssec-policy: nsec

  - domain: nsec3.test.
    dnssec-policy: nsec3

  - domain: optout-nsec3.test.
    dnssec-policy: optout-nsec3
