options {
    max-cache-size 10M;
    minimal-responses yes;

    listen-on-v6 { none; };
    listen-on port 5366 { 127.0.0.1; };

    allow-recursion { none; };
    allow-transfer { any; };
};

zone unsigned.test {
	type master;
	file "unsigned.test.zone";
};

zone nsec.test. {
	type master;
	file "nsec.test.zone.signed";
};

zone nsec3.test. {
	type master;
	file "nsec3.test.zone.signed";
};

zone optout-nsec3.test. {
	type master;
	file "optout-nsec3.test.zone.signed";
};
