options {
    max-cache-size 10M;

    listen-on-v6 { none; };
    listen-on port 5366 { 127.0.0.1; };

    allow-recursion { none; };
};

zone unsigned.test {
	type master;
	file "unsigned.test.zone";
};

zone nsec.test. {
	type master;
	file "nsec.test.zone.signed";
};
